// svelte/src/routes/sellers/[slug]/+page.svelte
<script>let { data } = $props();</script>
<div>
  <a href="/sellers" class="text-blue-600 hover:underline">&larr; Back to Sellers</a>
  <div class="mt-6">
    <div class="bg-white rounded-lg shadow p-6 mb-6">
      <h1 class="text-3xl font-bold mb-2">{data.name}</h1>
      <div class="flex gap-6 text-sm text-gray-500"><span>Rating: {data.rating.toFixed(1)}</span><span>{data.salesCount.toLocaleString()} sales</span><span>{data.location}</span></div>
    </div>
    <h2 class="text-2xl font-bold mb-4">Listings ({data.total})</h2>
    <div class="bg-white rounded-lg shadow overflow-x-auto">
      <table class="w-full">
        <thead class="bg-gray-50"><tr><th class="px-4 py-3 text-left text-sm font-semibold">Card</th><th class="px-4 py-3 text-left text-sm font-semibold">Condition</th><th class="px-4 py-3 text-right text-sm font-semibold">Price</th><th class="px-4 py-3 text-right text-sm font-semibold">Qty</th></tr></thead>
        <tbody class="divide-y">
          {#each data.listings as listing}
            <tr class="hover:bg-gray-50"><td class="px-4 py-3">{listing.cardId}</td><td class="px-4 py-3 text-sm">{listing.condition}</td><td class="px-4 py-3 text-right font-semibold">${listing.price.toFixed(2)}</td><td class="px-4 py-3 text-right text-sm">{listing.quantity}</td></tr>
          {/each}
        </tbody>
      </table>
    </div>
  </div>
</div>

// nuxt/pages/sellers/[slug].vue
<script setup lang="ts">
const route = useRoute();
const { data } = await useFetch(`/api/sellers/${route.params.slug}`);
</script>
<template>
  <div v-if="data">
    <NuxtLink to="/sellers" class="text-blue-600 hover:underline">&larr; Back to Sellers</NuxtLink>
    <div class="mt-6">
      <div class="flex items-center gap-4 mb-6">
        <div class="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center"><span class="text-2xl font-bold">{{ data.name[0] }}</span></div>
        <div><h1 class="text-3xl font-bold">{{ data.name }}</h1><p class="text-gray-600">{{ data.totalListings }} listings | ★ {{ data.rating.toFixed(1) }}</p></div>
      </div>
      <div class="overflow-x-auto">
        <table class="w-full text-sm">
          <thead><tr class="border-b"><th class="text-left py-2">Card</th><th class="text-left py-2">Game</th><th class="text-left py-2">Condition</th><th class="text-right py-2">Price</th></tr></thead>
          <tbody>
            <tr v-for="listing in data.listings" :key="listing.id" class="border-b hover:bg-gray-50">
              <td class="py-2"><NuxtLink :to="`/cards/${listing.cardId}`" class="text-blue-600 hover:underline">{{ listing.cardName }}</NuxtLink></td>
              <td class="py-2">{{ listing.gameName }}</td>
              <td class="py-2">{{ listing.condition }}</td>
              <td class="py-2 text-right font-semibold">${{ listing.price.toFixed(2) }}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>
