// svelte/src/routes/cards/[id]/+page.svelte
<script>let { data } = $props();</script>
<div>
  <a href="/search" class="text-blue-600 hover:underline mb-6 block">&larr; Back to Search</a>
  <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
    <div class="lg:col-span-1">
      <div class="bg-white rounded-lg shadow p-4">
        <div class="aspect-[3/4] bg-gray-100 rounded flex items-center justify-center"><span class="text-gray-400">{data.card.number}</span></div>
      </div>
    </div>
    <div class="lg:col-span-2">
      <div class="bg-white rounded-lg shadow p-6 mb-6">
        <h1 class="text-3xl font-bold mb-2">{data.card.name}</h1>
        <p class="text-gray-600 mb-4">{data.game?.name} | {data.set?.name || data.card.setId} | {data.card.number}</p>
        <div class="grid grid-cols-2 gap-4 mb-6">
          <div><span class="text-sm text-gray-500">Rarity</span><p class="font-semibold">{data.card.rarity}</p></div>
          <div><span class="text-sm text-gray-500">Type</span><p class="font-semibold">{data.card.type}</p></div>
        </div>
        {#if data.card.lowestPrice}
          <div class="border-t pt-4">
            <span class="text-sm text-gray-500">Starting from</span>
            <p class="text-2xl font-bold text-green-600">${data.card.lowestPrice.toFixed(2)}</p>
            <p class="text-sm text-gray-500">{data.card.listingCount} listings available</p>
          </div>
        {/if}
      </div>
      <div class="bg-white rounded-lg shadow">
        <div class="p-4 border-b"><h2 class="text-xl font-bold">Available Listings</h2></div>
        <div class="overflow-x-auto">
          <table class="w-full">
            <thead class="bg-gray-50">
              <tr><th class="px-4 py-3 text-left text-sm font-semibold">Seller</th><th class="px-4 py-3 text-left text-sm font-semibold">Condition</th><th class="px-4 py-3 text-left text-sm font-semibold">Language</th><th class="px-4 py-3 text-right text-sm font-semibold">Price</th><th class="px-4 py-3 text-right text-sm font-semibold">Qty</th></tr>
            </thead>
            <tbody class="divide-y">
              {#each data.card.listings.slice(0, 20) as listing}
                {@const seller = data.sellers.find(s => s.id === listing.sellerId)}
                <tr class="hover:bg-gray-50">
                  <td class="px-4 py-3">{seller?.name || 'Unknown'}</td>
                  <td class="px-4 py-3 text-sm">{listing.condition}</td>
                  <td class="px-4 py-3 text-sm">{listing.language}</td>
                  <td class="px-4 py-3 text-right font-semibold">${listing.price.toFixed(2)}</td>
                  <td class="px-4 py-3 text-right text-sm">{listing.quantity}</td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

// nuxt/pages/cards/[id].vue
<script setup lang="ts">
const route = useRoute();
const { data } = await useFetch(`/api/cards/${route.params.id}`);
</script>
<template>
  <div v-if="data">
    <NuxtLink :to="`/sets/${data.setSlug}`" class="text-blue-600 hover:underline">&larr; Back to {{ data.setName }}</NuxtLink>
    <div class="mt-6 grid grid-cols-1 md:grid-cols-2 gap-8">
      <div class="bg-gray-100 rounded-lg aspect-[3/4] flex items-center justify-center"><span class="text-gray-400 text-2xl">{{ data.number }}/{{ data.setTotalCards || 200 }}</span></div>
      <div>
        <h1 class="text-3xl font-bold mb-2">{{ data.name }}</h1>
        <div class="space-y-2 mb-6">
          <p class="text-gray-600">Rarity: <span class="font-semibold">{{ data.rarity }}</span></p>
          <p class="text-gray-600">Number: <span class="font-semibold">{{ data.number }}</span></p>
          <p class="text-gray-600">Set: <span class="font-semibold">{{ data.setName }}</span></p>
          <p class="text-gray-600">Game: <span class="font-semibold">{{ data.gameName }}</span></p>
        </div>
        <h2 class="text-xl font-bold mb-4">Listings ({{ data.listings?.length || 0 }})</h2>
        <div class="overflow-x-auto">
          <table class="w-full text-sm">
            <thead><tr class="border-b"><th class="text-left py-2">Seller</th><th class="text-left py-2">Condition</th><th class="text-right py-2">Price</th></tr></thead>
            <tbody>
              <tr v-for="listing in data.listings" :key="listing.id" class="border-b">
                <td class="py-2"><NuxtLink :to="`/sellers/${listing.sellerSlug}`" class="text-blue-600 hover:underline">{{ listing.sellerName }}</NuxtLink></td>
                <td class="py-2">{{ listing.condition }}</td>
                <td class="py-2 text-right font-semibold">${{ listing.price.toFixed(2) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</template>
