// nuxt/pages/cart.vue
<template>
  <div>
    <h1 class="text-3xl font-bold mb-8">Shopping Cart</h1>
    <div class="bg-white rounded-lg shadow p-8 text-center">
      <p class="text-gray-500 mb-4">Your cart is empty</p>
      <NuxtLink to="/search" class="inline-block bg-blue-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-blue-700 transition no-underline">Browse Cards</NuxtLink>
    </div>
  </div>
</template>

// svelte/src/routes/cart/+page.svelte
<div>
  <h1 class="text-3xl font-bold mb-8">Shopping Cart</h1>
  <div class="bg-white rounded-lg shadow p-8 text-center">
    <p class="text-gray-500 mb-4">Your cart is empty</p>
    <a href="/search" class="inline-block bg-blue-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-blue-700 transition no-underline">Browse Cards</a>
  </div>
</div>
