// svelte/src/routes/games/+page.svelte
<script>let { data } = $props();</script>
<div>
  <h1 class="text-3xl font-bold mb-8">All Games</h1>
  <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-6">
    {#each data.games as game}
      <a href="/games/{game.slug}" class="bg-white rounded-lg shadow p-6 hover:shadow-md transition no-underline text-inherit">
        <div class="aspect-square bg-gray-100 rounded mb-4 flex items-center justify-center"><span class="text-4xl">{game.name.charAt(0)}</span></div>
        <h2 class="font-bold text-lg text-center mb-1">{game.name}</h2>
        <p class="text-sm text-gray-500 text-center">{game.cardCount.toLocaleString()} cards</p>
        <p class="text-xs text-gray-400 text-center mt-2">{game.description}</p>
      </a>
    {/each}
  </div>
</div>

// react-router/app/routes/games.tsx
import { Link } from "react-router";
import { db } from "../lib/db";
import type { Route } from "./+types/games";

export async function loader() {
  const games = await db.getGames();
  return { games };
}

export default function GamesPage({ loaderData }: Route.ComponentProps) {
  const { games } = loaderData;

  return (
    <div>
      <h1 className="text-3xl font-bold mb-8">All Games</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {games.map((game) => (
          <Link
            key={game.id}
            to={`/games/${game.slug}`}
            className="bg-white rounded-lg shadow-md p-6 hover:shadow-lg transition"
          >
            <div className="aspect-video bg-gray-100 rounded mb-4 flex items-center justify-center">
              <span className="text-5xl font-bold text-gray-300">
                {game.name.charAt(0)}
              </span>
            </div>
            <h2 className="text-xl font-bold mb-2">{game.name}</h2>
            <p className="text-gray-600 mb-4">{game.description}</p>
            <p className="text-sm text-blue-600">
              {game.cardCount.toLocaleString()} cards available
            </p>
          </Link>
        ))}
      </div>
    </div>
  );
}
