// svelte/src/routes/sellers/+page.svelte
<script>let { data } = $props();</script>
<div>
  <h1 class="text-3xl font-bold mb-8">Sellers</h1>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    {#each data.sellers as seller}
      <a href="/sellers/{seller.slug}" class="bg-white rounded-lg shadow p-6 hover:shadow-md transition no-underline text-inherit">
        <h2 class="font-bold text-lg mb-2">{seller.name}</h2>
        <div class="flex justify-between text-sm text-gray-500"><span>Rating: {seller.rating.toFixed(1)}</span><span>{seller.salesCount.toLocaleString()} sales</span></div>
        <p class="text-xs text-gray-400 mt-2">{seller.location}</p>
      </a>
    {/each}
  </div>
</div>

// react-router/app/routes/sellers.tsx
import { Link } from "react-router";
import { db } from "../lib/db";
import type { Route } from "./+types/sellers";

export async function loader() {
  const sellers = await db.getSellers();
  // Sort by rating descending
  const sortedSellers = [...sellers].sort((a, b) => b.rating - a.rating);
  return { sellers: sortedSellers };
}

export default function SellersPage({ loaderData }: Route.ComponentProps) {
  const { sellers } = loaderData;

  return (
    <div>
      <h1 className="text-3xl font-bold mb-8">Marketplace Sellers</h1>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {sellers.map((seller) => (
          <Link
            key={seller.id}
            to={`/sellers/${seller.slug}`}
            className="bg-white rounded-lg shadow p-6 hover:shadow-md transition"
          >
            <div className="flex items-start justify-between mb-4">
              <div>
                <h2 className="text-xl font-bold">{seller.name}</h2>
                <p className="text-sm text-gray-500">{seller.location}</p>
              </div>
              <div className="text-right">
                <div className="flex items-center gap-1">
                  <span className="text-yellow-500">&#9733;</span>
                  <span className="font-bold">{seller.rating.toFixed(1)}</span>
                </div>
              </div>
            </div>
            <p className="text-sm text-gray-600">
              {seller.salesCount.toLocaleString()} sales completed
            </p>
          </Link>
        ))}
      </div>
    </div>
  );
}
